let latestproductData = [
    {
        id: 111,
        name: "Apple-iPhone-11-Pro-Max",
        img: "assets/images/Apple-iPhone-11-Pro-Max.jpg",
        rating: 4.5,
        brand: "Apple ",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1500, 
        feature: true,
    },
    {
        id: 112,
        name: " Apple-iPhone-12-Pro-Max",
        img: "assets/images/Apple-iPhone-12-Pro-Max.jpg",
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1300,
        feature: true,
    },
    {
        id: 113,
        name: "Apple-iPhone-13-Pro-Max",
        img: "assets/images/Apple-iPhone-13-Pro-Max-image.jpg",
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 2000,
        feature: false,
    },
    {
        id: 114,
        name: "Apple-iPhone-14-Pro-Max",
        img: "assets/images/Apple-iPhone-14-Pro-Max.jpg",
        rating: 4,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 3600,
        feature: false,
    },
]
module.exports = latestproductData;