import women1 from "../assets/images/women1.jpg"
import women2 from "../assets/images/women2.jpg"
import women3 from "../assets/images/women3.jpg"
import women4 from "../assets/images/women4.jpg"
import man1 from "../assets/images/man1.jpg"
import man2 from "../assets/images/man2.jpg"
import man3 from "../assets/images/man3.jpg"
import man4 from "../assets/images/man4.jpg"
import child1 from "../assets/images/child1.jpg"
import child2 from "../assets/images/child2.jpg"
import child3 from "../assets/images/child3.jpg"
import child4 from "../assets/images/child4.jpg"
import accessories1 from '../assets/images/product14.jpg'
import accessories2 from '../assets/images/product15.jpg'
import accessories3 from '../assets/images/product16.jpg'
import accessories4 from '../assets/images/product17.jpg'
import latest1 from "../assets/images/Apple-iPhone-11-Pro-Max.jpg"
import latest2 from "../assets/images/Apple-iphone-12-Pro-Max.jpg"
import latest3 from "../assets/images/Apple-iPhone-13-Pro-Max-image.jpg"
import latest4 from "../assets/images/Apple-iPhone-14-Pro-Max.jpg"
import latest5 from "../assets/images/Apple-iPhone-13-Pro-Max-image.jpg"
export const productData = [
    {
        id: 1,
        name: "Woolen T-Shirt",
        img: women1,
        rating: 4.5,
        brand: "zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1000, 
        feature: true,
    },
    {
        id: 2,
        name: "Woolen T-Shirt",
        img: women2,
        rating: 4.5,
        brand: "zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1300,
        feature: true,
    },
    {
        id: 3,
        name: "Woolen T-Shirt",
        img: women3,
        rating: 4.5,
        brand: "zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1100,
        feature: false,
    },
    {
        id: 4,
        name: "Woolen T-Shirt",
        img: women4,
        rating: 4,
        brand: "zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 600,
        feature: false,
    },
    {
        id: 5,
        name: "Mens T-Shirt",
        img: man1,
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 600,
        feature: false,
    },
    {
        id: 6,
        name: "Mens Shirt",
        img: man2,
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 500,
        feature: false,
    },
    {
        id: 7,
        name: "Formal Shirt",
        img: man3,
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 500,
        feature: false,
    },
    {
        id: 8,
        name: "Mens Pant",
        img: man4,
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 550,
        feature: false,
    },
    {
        id: 9,
        name: "Baby Dress",
        img: child1,
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 4000, 
        feature: false,
    },
    {
        id: 10,
        name: "Baby Dress",
        img: child2,
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 3750,
        feature: false,
    },
    {
        id: 11,
        name: "Baby Dress",
        img: child3,
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 4500,
        feature: false,
    },
    {
        id: 12,
        name: "Baby Dress",
        img: child4,
        rating: 5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 3800,
        feature: false,
    },
    {
        id: 13,
        name: "Gold Stainless Steel Case with Sport Band",
        img: accessories1,
        rating: 5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 30000,
        feature: true,
    },
    {
        id: 14,
        name: "Midnight Aluminum Case with Sport Band",
        img: accessories2,
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 25000,
        feature: true,
    },
    {
        id: 15,
        name: "Starlight Aluminum Case with Solo Loop",
        img: accessories3,
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 20000,
        feature: false,
    },
    {
        id: 16,
        name: "Graphite Stainless Steel Case with Leather Link",
        img: accessories4,
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 20000,
        feature: false,
    },
    {
        id: 17,
        name: "Apple-iPhone-11-Pro-Max",
        img: latest1,
        rating: 4.5,
        brand: "Apple ",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1500, 
        feature: true,
    },
    {
        id: 18,
        name: " Apple-iPhone-12-Pro-Max",
        img: latest2,
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1300,
        feature: true,
    },
    {
        id: 19,
        name: "Apple-iPhone-13-Pro-Max",
        img: latest3,
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 2000,
        feature: false,
    },
    {
        id: 20,
        name: "Apple-iPhone-14-Pro-Max",
        img: latest4,
        rating: 4,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 3600,
        feature: false,
    },
    {
        id: 21,
        name: "Apple-iPhone-14-Pro-Max",
        img: latest5,
        rating: 4,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 3600,
        feature: false,
    },
]
