let productData = [
    {
        id: 1,
        name: "Woolen T-Shirt",
        img: "assets/images/women1.jpg",
        rating: 4.5,
        brand: "zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1000, 
        feature: true,
    },
    {
        id: 2,
        name: "Woolen T-Shirt",
        img: "assets/images/women2.jpg",
        rating: 4.5,
        brand: "zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1300,
        feature: true,
    },
    {
        id: 3,
        name: "Woolen T-Shirt",
        img: "assets/images/women3.jpg",
        rating: 4.5,
        brand: "zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 1100,
        feature: false,
    },
    {
        id: 4,
        name: "Woolen T-Shirt",
        img: "assets/images/women4.jpg",
        rating: 4,
        brand: "zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 600,
        feature: false,
    },
    {
        id: 5,
        name: "Mens T-Shirt",
        img: "assets/images/man1.jpg",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 600,
        feature: false,
    },
    {
        id: 6,
        name: "Mens Shirt",
        img: "assets/images/man2.jpg",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 500,
        feature: false,
    },
    {
        id: 7,
        name: "Formal Shirt",
        img: "assets/images/man3.jpg",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 500,
        feature: false,
    },
    {
        id: 8,
        name: "Mens Pant",
        img: "assets/images/man4.jpg",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 550,
        feature: false,
    },
    {
        id: 9,
        name: "Baby Dress",
        img: "assets/images/child1.jpg",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 4000, 
        feature: false,
    },
    {
        id: 10,
        name: "Baby Dress",
        img: "assets/images/child2.jpg",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 3750,
        feature: false,
    },
    {
        id: 11,
        name: "Baby Dress",
        img: "assets/images/child3.jpg",
        rating: 4.5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 4500,
        feature: false,
    },
    {
        id: 12,
        name: "Baby Dress",
        img: "assets/images/child4.jpg",
        rating: 5,
        brand: "Zara",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 3800,
        feature: false,
    },
    {
        id: 13,
        name: "Gold Stainless Steel Case with Sport Band",
        img: "assets/images/product14.jpg",
        rating: 5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 30000,
        feature: true,
    },
    {
        id: 14,
        name: "Midnight Aluminum Case with Sport Band",
        img: "assets/images/product15.jpg",
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 25000,
        feature: true,
    },
    {
        id: 15,
        name: "Starlight Aluminum Case with Solo Loop",
        img: "assets/images/product16.jpg",
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 20000,
        feature: false,
    },
    {
        id: 16,
        name: "Graphite Stainless Steel Case with Leather Link",
        img: "assets/images/product17.jpg",
        rating: 4.5,
        brand: "Apple",
        color: ["622060", "1437A9", "FBDADA", "519d04"],
        sizes:['xs', 's', 'm'],
        price: 20000,
        feature: false,
    },
]
module.exports = productData;